// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fljlpkmtvigsdjbbihwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsamxwa210dmlnc2RqYmJpaHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMjEyNzQsImV4cCI6MjA0OTY5NzI3NH0.oR4BreLy-xzs1LJUjmcxXx6wzTMCFLK6cqPazNtIFRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);